# Generated by Django 2.2.4 on 2020-03-31 10:59

from django.db import migrations


def new_building_auto(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.new_building = False
        if flat.construction_year >= 2015:
            flat.new_building = True
        flat.save()


def new_building_backward(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.new_building = None
        Flat.save()


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(new_building_auto, new_building_backward),
    ]
