# Generated by Django 2.2.4 on 2020-03-31 17:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_flat_liked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='liked_by',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='users_liked',
                                         to=settings.AUTH_USER_MODEL, verbose_name='Кло лайкнул'),
        ),
    ]
