# Generated by Django 2.2.4 on 2020-03-31 18:18

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20200331_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='owner_phone_pure',
            field=phonenumber_field.modelfields.PhoneNumberField(null=True,blank=True, max_length=128, region=None, db_index=True),
        ),
    ]
