# Generated by Django 2.2.4 on 2020-03-31 20:02

from django.db import migrations
import phonenumbers

def normalize_phone_number(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        normalized_number = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        formatted_number = None
        if phonenumbers.is_valid_number(normalized_number):
            formatted_number = phonenumbers.format_number(
                normalized_number,
                phonenumbers.PhoneNumberFormat.E164
            )
        flat.owner_phone_pure = formatted_number
        flat.save()


def phone_number_backward(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.owner_phone_pure = None
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_flat_owner_phone_pure'),
    ]

    operations = [
        migrations.RunPython(
            normalize_phone_number,
            phone_number_backward
        )
    ]
