# Generated by Django 2.2.4 on 2020-03-31 22:16

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0011_auto_20200331_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')),
                ('name', models.CharField(
                    max_length=200, verbose_name='ФИО владельца',
                    db_index=True)),
                ('phonenumber', models.CharField(
                    max_length=20, verbose_name='Номер владельца',
                    db_index=True)),
                ('phone_pure', phonenumber_field.modelfields.PhoneNumberField(
                    blank=True,
                    verbose_name='Нормализованный номер владельца',
                    max_length=128, null=True, region=None,
                    db_index=True)),
                ('flats', models.ManyToManyField(
                    related_name='flat_owners',
                    to='property.Flat', db_index=True,
                    verbose_name='Квартиры в собственности')),
            ],
        ),
    ]
