# Generated by Django 2.2.4 on 2020-04-01 12:30

from django.db import migrations


def load_data_from_flat(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        Owner.objects.get_or_create(name=flat.owner, phonenumber=flat.owners_phonenumber,
                                    phone_pure=flat.owner_phone_pure,
                                    defaults={
                                        'name': flat.owner,
                                        'phonenumber': flat.owners_phonenumber,
                                        'phone_pure': flat.owner_phone_pure,
                                    }
                                    )


def data_backward(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Owner.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0013_owner'),
    ]

    operations = [
        migrations.RunPython(load_data_from_flat, data_backward)
    ]
