# Generated by Django 2.2.4 on 2020-04-02 08:16

from django.db import migrations


def transfer_data_about_owner(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')
    for owner in Owner.objects.all():
        flats_in_property = Flat.objects.filter(owner=owner.name)
        owner.flats.set(flats_in_property)


def transfer_data_about_flat(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat_owners = flat.flat_owners.all()
        flat.owners.set(flat_owners)


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0014_flat_owners'),
    ]

    operations = [
        migrations.RunPython(transfer_data_about_owner),
        migrations.RunPython(transfer_data_about_flat),
    ]
