# Generated by Django 2.2.4 on 2020-04-02 08:16

from django.db import migrations


def transfer_data_about_owner(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')
    owners = Owner.objects.all()
    for owner in owners:
        flats_in_property = Flat.objects.filter(owner=owner.name, owners_phonenumber=owner.phonenumber)
        owner.flats.set(flats_in_property)
        owner.save()


def transfer_data_about_flat(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects.all()
    for flat in flats:
        flat_owners = flat.flat_owners.all()
        flat.owners.set(flat_owners)
        flat.save()


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0015_flat_owners'),
    ]

    operations = [
        migrations.RunPython(transfer_data_about_owner),
        migrations.RunPython(transfer_data_about_flat),
    ]
