# Generated by Django 2.2.4 on 2020-04-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_auto_20200402_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='flats',
            field=models.ManyToManyField(
                blank=True, db_index=True, related_name='flat_owners',
                to='property.Flat', verbose_name='Квартиры в собственности'),
        ),
    ]
